travis:
  secure:
    BINSTAR_TOKEN: BmyfSDXlFC2wqkM1ddADzM2xy6b4vgEPeOBHpZrbfAPyt8aHF3jX7/CE7wjSbsZ0S/8KyUyxRE9G6FtiaTYsXBrN1GgwLfBzO/9ftKDN/Cbm4WOG008AYrglmJXApxkMCINeyPWwt5sfkbS+3K0jIo3hvobG9OikIVVAmwScwylvGeEnNQQLTsrp30OYxrxTxqyQIE/Zy3WZRXOSDjkc25l58q9g+CkmxSDZMT99leETHUe31wyqrznfpy9rpgp3R/rOXdCkaW2iMWbE4pugKBMLmRNs33fwyTk0Fh8MoiDEH+/7Yv5Q/WyhtrHJa3ZPPKC3hDSFUB1YsMCWj0hGen1G1woDybmqKmi+esPVZqvV+TgS0v6FJqzE2B+PopwiHpQO2gk0nwxvs1UFfPVsLX1QpgE3dW8B+ix9vTjrwEnL8274j0i3HwqSi1PRUQg9pMnZJioNPo8YfIAv8nwF60YIBa4EyZR0dkBTfJrSevquTzEDNuhuEVVmP64XF6LYwMnqJlv89h3woAdoLtrHn9tB6uWi32SibZxceKE8CSUCzT7PMe+GSS/H2Vg+DwtAwv7ObTomH4Z9XAcI1cvyZ05d5HFiH/eUPORz21GjR2wWEDzELD/MK55vtIkYuTGvuzLhD0lOjhLjAjqxxZ1hgRHdj/DxcC6F3TzRZfdA92Y=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
conda_forge_output_validation: true
